#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TicTacToe.Resource", IsApplication=true)]

namespace TicTacToe
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040003
			public const int available_color = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int blue_color = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int border_color = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int dark_border_color = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int field_color = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int gray_color = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int purple_color = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int red_color = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int thinking_background_color = 2130968584;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_vertical_margin = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int control_padding = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int corner_radius = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int elevation_high = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int elevation_low = 2131034120;
			
			// aapt resource value: 0x7f050010
			public const int menu_button_margin = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int menu_button_padding = 2131034129;
			
			// aapt resource value: 0x7f05000d
			public const int menu_padding = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int menu_space = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int menu_text_size = 2131034127;
			
			// aapt resource value: 0x7f050007
			public const int small_board_margin = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int small_board_padding = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int stroke_width = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int thinking_progress_size = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int tile_margin = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int tile_padding = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int tile_size = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int menu_background = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080003
			public const int about_button = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int continue_button = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int main_fragment = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int new_button = 2131230722;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060009
			public const int about_label = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int about_text = 2131099659;
			
			// aapt resource value: 0x7f060008
			public const int about_title = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int action_settings = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int continue_label = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int declare_winner = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int long_app_name = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int main_menu_label = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int new_game_label = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int ok_label = 2131099658;
			
			// aapt resource value: 0x7f060003
			public const int restart_label = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
